services:
    # PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env        
        volumes:
            - .:/var/www
        ports:
            - ${PHP_PORT1}:${PHP_PORT2}
        depends_on:
            - mariadb
        networks:
            - licitacao-net
        #command: php artisan serve   

    # db mariadb
    mariadb:
        image: mariadb:latest
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - mariadb_data:/var/lib/mysql        
        command:
            --max_allowed_packet=32505856
        networks:
            - licitacao-net

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
            - '${NGINX_PORT:-8080}:${NGINX_PORT}'
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - licitacao-net

networks:
    licitacao-net:
        driver: bridge

volumes:
    mariadb_data:    
